# Generated by Django 5.2.6 on 2025-09-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['timestamp']},
        ),
    ]
